### ISSUE TITLE
Conditional compilation failing 

### ISSUE THREAD

**Issue by pankhurivanjani** [TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani#2]
Conditional compilation is failing. While building the package dummyexample [dummypackage](https://github.com/TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani/tree/master/dummyexample) using colcon buld --symlink-install
Getting the error indicating it is not taking ros.h header files 

pankhuri@pankhuri-LENOVO-IDEAPAD-500-15ISK:~/week2$ colcon build --symlink-install
Starting >>> dummyexample
--- stderr: dummyexample                             
In file included from /home/pankhuri/week2/main.cpp:4:
/home/pankhuri/week2/main.hpp:3:14: fatal error: 'ros/ros.h' file not found
    #include "ros/ros.h"
             ^~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/main.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/main.dir/all] Error 2
make: *** [all] Error 2

Failed   <<< dummyexample       [ Exited with code 2 ]

Summary: 0 packages finished [1.15s]
  1 package failed: dummyexample
  1 package had stderr output: dummyexample

**Comment by vinay0410** [comment]
https://github.com/TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani/blob/e0e70cdd209eb23af5dda0501dd13d7669618329/dummyexample/main.hpp#L6
and
https://github.com/TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani/blob/e0e70cdd209eb23af5dda0501dd13d7669618329/dummyexample/main.hpp#L1

Why are you using ifndef here ?

Also, don't you think you logic written in `main.cpp` is wrong.
What will happen if the user selects ROS2 and it's not installed. Nothing will happen.

**Comment by pankhurivanjani** [comment]
Changed ifndef with ifdef, but it is giving the inactive regions.

For the cases when the user selects ROS2 or ROS1 and it's not installed, I will be the throwing the exception siimlar to 'ROS2 not found'.

**Comment by vinay0410** [comment]
Yes, you should be throwing an exception. I didn't understand what do you mean by inactive regions, and what exactly are you trying to achieve here ?

**Comment by pankhurivanjani** [comment]
Inactive regions as I see in my vscode editor is like this:
![image](https://user-images.githubusercontent.com/28755817/59146535-cf14d380-8a0c-11e9-9c55-b329c094839e.png)
Anything useful or even some random keyword between #ifdef and #endif will be ignored while compiling.

To get both ROS1 and ROS2 working in different cases we want to use and build with their individual header files when we come through that case. 
To begin with I am using this case. Say, for case 1 when I select ROS:
I want to include ros/ros.h and other required header files and publish 'Hello World'. 
 
So, before increasing the complexity, I am just trying to make sure I am able to compile a few lines with this package.

**Comment by pankhurivanjani** [comment]
Updates:
Okay, so it was looking like an error of wrong directives. It was due to the placing of #define in wrong lines.
I have resolved this and understood the real problem now.

Real issue is:
fatal error: 'ros/ros.h' file not found
OR..
fatal error: 'rclcpp/rclcpp.hpp' file not found

These were coming because the environment path was not yet sourced.

After doing:
source /opt/ros/melodic/setup.bash
and then 
colcon build --symlink-install

errors reduced.
ROS1 got compiled. 

Now, a solution to this issue would be setting up CMake_Prefix_Path to ros/melodic and ros/dashing for respective cases using IF...Endif in CMakeLists.txt.

Similar has been done in [How to use ROS without a Catkin workspace] (http://dav.ee/blog/notes/archives/875) , but I don't have any workspace for ROS1 or ROS2 as I did the binary full desktop installation for ROS1 and ROS2.

Now, Is there a way:
to include the header files in CMakeLists.txt from /opt/ros/melodic or dashing /include ?
OR
source bash file from there in CMakeLists.txt (using SET(....))?

(The ways I tried didn't yield any success from /opt/ros/..)

Should I create new workspace and follow as given in link? What do you suggest @vinay0410 ?

**Comment by vinay0410** [comment]
As far as `#define` headers are concerned, you don't need to define them in `main.hpp`, because they are already defined in `CMakeLists.txt`, so redefining them doesn't make any sense.

Secondly all `source /opt/ros/melodic/setup.bash` does is alter environment variables like `PATH and LD_LIBRARY_PATH`(you can try running `echo $PATH` to see the difference), so that cmake easily finds the ROS libraries.
So, I believe that the CmakeLists file should be able to load ROS libraries without sourcing.

I think you can change `CMAKE_PREFIX_PATH` to point to `/opt/ros/dashing` for ROS and to `/opt/ros/melodic` for ROS1, that should load the libraries without sourcing.

Going forward we can improving the CMakeFiles to search for ROS2 libraries starting from most recent distros first.

Also, since we should have the capability to switch ROS version at runtime, without having to build this interface again, I believe sourcing wouldn't be a viable option.

Also, your CMakeLIsts.txt file is completely wrong.
https://github.com/TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani/blob/e0e70cdd209eb23af5dda0501dd13d7669618329/dummyexample/CMakeLists.txt#L16-L40

If else statements are ambiguous, and you are using `roscpp_FOUND` header before calling find_package(roscpp). Fix that and try to use `CMAKE_PREFIX_PATH`, in a fresh shell without souricng anything.

**Comment by pankhurivanjani** [comment]
Yes, after fixing the errors, conditional compilation is kind of working now.

Also, I fixed the issue for CMAKE_PREFIX_PATH for ROS1.

CMakeLists.txt had lot of errors which have been corrected now.
 Without sourcing, it is working well now. Just using /opt/ros/melodic wasn't giving right results, but after some research, I created a new workspace and changed the path to this:
 
SET(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH} /home/pankhuri/ros2_ws/install";/opt/ros/melodic) 

Before putting conditions in  CMakeLists.txt  I was doing the same for ROS2 but there are issues in it. There were errors due to ament_package.

ament_package is a Python module. Python uses the PYTHONPATH variable. It doesn't retrieve the CMAKE_PREFIX_PATH, so setting it will not extend the Python search path.

This requires a fix before finishing the logic of this task.

**Comment by pankhurivanjani** [comment]
Problem fixed for ROS2 too, without sourcing ROS2 environment from the shell, I can build the code.
Lines for ROS2 in CMakeLists.txt are :

SET(ENV{PYTHONPATH} "/opt/ros/dashing/lib/python3.6/site-packages/")
SET(CMAKE_PREFIX_PATH "${CMAKE_REFIX_PATH} home/pankhuri/ros2_ws/install;/opt/ros/dashing")

In this order only, since ament_package was getting import errors so the correct path needs to be set first.

Maybe another alternative was using AMENT_PREEFIX_PATH which would be better too since we should utilize ROS2 design features, but I was unable to solve the errors.
I have posted this on [answers.ros.org](http://answers.ros.org/question/325087/modulenotfounderror-no-module-named-ament_package/) and following similar posts. If it gets resolved, will look into it then

**Comment by pankhurivanjani** [comment]
Compilation errors have been resolved If we require some improvement in the code we can open that in another issue. So, Closing this issue for now.
