### ISSUE TITLE
Dockerfile for ROS1 + ROS2 

### ISSUE THREAD

**Issue by pankhurivanjani** [TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani#3]
I have tried a few approached in creating a new dockerfile for both distros, but could not complete it. 
In first I read about multiple containers and implemented after following this link [docker-compose](https://www.linux.org/threads/docker-compose.23562/?fbclid=IwAR2k5OB6GzXVAHoxhuTZrde8Bqh5W8kDDMs7DMoZ-uknVxd66NKDvXO8RcY) but it exits after starting.
The file can be found here: [approach-2](https://github.com/TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani/tree/master/Dockerfiles/ROS1%2BROS2%20docker/Approach2)
Output can be seen on the blog: [blog](https://theroboticsclub.github.io/colab-gsoc2019-Pankhuri_Vanjani/2019-06-13-soccer/)

In another approach, I tried downloading both distros in a ubuntu image and used entrypoints script for ROS1 and ROS2 respectively. I thought I would create custom images in this way and enter into distros using entry points. But it just resulted in ROS2 environment.

Code: [approach-4](https://github.com/TheRoboticsClub/colab-gsoc2019-Pankhuri_Vanjani/tree/master/Dockerfiles/ROS1%2BROS2%20docker/Approach-4)

**Comment by vinay0410** [comment]
Also, I am not very clear as to what you are trying to achieve here. What exactly do you want to run inside your docker containers ?

**Comment by jmplaza** [comment]
I guess that the target is to have a portable development environment to work with systems with only ROS1 (docker1), to have another one to work with systems with only ROS2 (docker2). That way she could easily test the compatibility issues of the tools in both scenarios.

In addition with the docker3 (with both ROS1 and ROS2 installed) maybe we could test the switching between ROS1 and ROS2 at run time (in the future).
